# Generated by Django 5.2.8 on 2025-11-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedLabelPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=500)),
                ('removed_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidLabelPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=500)),
                ('label_status', models.CharField(choices=[('valid', 'Valid'), ('not_checked', 'Not Checked')], default='not_checked', max_length=20)),
            ],
        ),
    ]
